on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DNOHUB_USERNAME: ${{ secrets.DNOHUB_USERNAME }}
      DNOHUB_PASSWORD: ${{ secrets.DNOHUB_PASSWORD }}
      MASTER_IP: ${{ secrets.HOST }}
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p skymp5-server
            cd skymp5-server
            mkdir -p $GITHUB_SHA && cd $GITHUB_SHA
            rm -rf .git
            git init
            git remote add origin https://$DNOHUB_USERNAME:$DNOHUB_PASSWORD@github.com/$GITHUB_REPOSITORY.git
            git fetch origin $GITHUB_SHA
            git reset --hard FETCH_HEAD
            docker build -t skymp5-server .
            rm -rf $GITHUB_SHA
            docker rm -f scamp || true
            docker run -p 7777:7777/udp --name scamp --restart always -dit skymp5-server npm run start-prod -- --master http://$MASTER_IP:3000 --name Nirnroot
          envs: GITHUB_SHA,GITHUB_REPOSITORY,DNOHUB_USERNAME,DNOHUB_PASSWORD,MASTER_IP
          script_stop: true
          command_timeout: 6h
