on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    env:
      buildDir: "${{ github.workspace }}/build/"
    steps:
      - uses: actions/checkout@master
        with:
          submodules: "recursive"
          fetch-depth: 0
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile # Remember to give an ID if you need the output
        name: Download the file
        with:
          url: "https://cef-builds.spotifycdn.com/cef_binary_84.3.7%2Bg97011bc%2Bchromium-84.0.4147.89_windows64.tar.bz2"
          target: cef_download/
      - run: ls cef_download/
      - run: 7z x cef_binary_84.3.7%2Bg97011bc%2Bchromium-84.0.4147.89_windows64.tar.bz2
        working-directory: cef_download/
      - run: 7z x cef_binary_84.3.7%2Bg97011bc%2Bchromium-84.0.4147.89_windows64.tar
        working-directory: cef_download/
      - run: ls cef_download/
      #-uses: actions/cache@v1   <===== YOU DO NOT NEED THIS!

      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install dev_service dependencies
        working-directory: ./tools/dev_service
        run: npm install

      - name: Run CMake to generate project file and build the project
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: "CMakeLists.txt"
          buildDirectory: ${{ env.buildDir }}
          # This input tells run-cmake to consume the vcpkg.cmake toolchain file set by run-vcpkg.
          useVcpkgToolchainFile: true
          buildWithCMake: true
          buildWithCMakeArgs: "--config Release"
      - name: Use dev_service to pack everything into a dist directory
        working-directory: ./tools/dev_service
        run: npm run pack

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Get SHA short
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Create an archive
        shell: bash
        run: |
          mkdir ./builds
          7z a -t7z -mx=9 ./builds/skyrim-platform-${{ steps.previoustag.outputs.tag }}-${{ steps.vars.outputs.sha_short }}.7z ./tools/dev_service/dist/*
      - run: ls .
      - run: ls ./tools/dev_service/dist
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "skyrim-platform-builds"
          source_dir: "./builds"
          destination_dir: ""
