on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
          fetch-depth: 0
      - run: docker build --tag skymp5-server .
      - run: docker run skymp5-server npm run test
      - name: Push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-3
          local-image: skymp5-server
          image: skymp5-server:$GITHUB_SHA
  build-win32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
          fetch-depth: 0
      - run: npm i
      - run: npm run configure
      - run: npm run build-prod
      - run: npm run test
      - run: npm run pack
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Get SHA short
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Create an archive
        shell: bash
        run: |
          mkdir ./archive-folder
          7z a -t7z -mx=9 ./archive-folder/skymp-server-lite-win32-${{ steps.previoustag.outputs.tag }}-${{ steps.vars.outputs.sha_short }}.7z ./pack/*
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "skymp-server-lite-win32-builds"
          source_dir: "./archive-folder"
          destination_dir: ""
  pack-client-dist:
    needs: [build-win32]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: actions/checkout@master
        with:
          submodules: true
          fetch-depth: 0
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Get SHA short
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Create a Distribution
        shell: bash
        run: |
          mkdir client-dist
          cd client-dist
        # Extract MpClientPlugin.dll, skymp5-client.js from the server distribution
          wget https://skymp-server-lite-win32-builds.s3.eu-west-2.amazonaws.com/skymp-server-lite-win32-${{ steps.previoustag.outputs.tag }}-${{ steps.vars.outputs.sha_short }}.7z
          7z x skymp-server-lite-win32-${{ steps.previoustag.outputs.tag }}-${{ steps.vars.outputs.sha_short }}.7z
          rm skymp-server-lite-win32-${{ steps.previoustag.outputs.tag }}-${{ steps.vars.outputs.sha_short }}.7z
          mkdir -p Data/Platform/Plugins
          mkdir -p Data/SKSE/Plugins
          mv dist_front/skymp5-client.js Data/Platform/Plugins
          mv MpClientPlugin.dll Data/SKSE/Plugins
          ls | grep -v Data | parallel rm -r
        # Create 'skymp5-client-settings.txt'
          cp ../skymp5-client-settings.txt Data/Platform/Plugins
        # Extract everything from Skyrim Platform
          wget -O sp.7z https://skyrim-platform-builds.s3.eu-west-2.amazonaws.com/skyrim-platform-$(node -p "JSON.parse(require('fs').readFileSync('package.json')).versionSkyrimPlatform").7z
          7z x sp.7z
          rm sp.7z
        # Copy everything from client dependencies (like 3-rd party SKSE plugins)
          cp -r ../client_deps/* .
        # List files for debugging purposes:
          ls -R