on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - run: docker build --tag skymp5-server .
      - run: docker run skymp5-server npm run test
